### ISSUE TITLE
Mod Settings not retained

### ISSUE THREAD

**Issue by badtouchatr** [ClaudeMetz/FactoryPlanner#135]
### Problem Description

The "per player" mod settings, specifically the Interface height, is not being retained between saves.  Somtimes, it will reset even while in game.

### Reproduction

I must've set the height to 14 at some point, but now I want it at the default of 24.  When i click the reset to default button, click confoirm, and go back in game, it works for a while, then when pulling up the interface again, it has reset to 14.

  I am on version 1.1.72 of Factory Planner, and am playing with the Pyanodon's Alternative Energy mod pack (full suite), if that makes a difference.  Thanks!

**Comment by badtouchatr** [comment]
You know, after some more messing around with this, I realized that I could make this "bug" happen just by tabbing out of Factorio into another window on my machine.  So, it could be a host of other issues causing this problem, maybe Steam, maybe my Ubuntu system, who knows.  Sorry, and I will deal with this until I figure something out.  Thanks again for a great mod!

**Comment by ClaudeMetz** [comment]
Hello, very sorry for not replying to you earlier. I think I know why this is: The mod has some logic to make sure the main interface always fits the player's screen. Do achieve that, every time the window size changes, it scales down the interface until it fits. I feel like the issue here is that the OS resizes the interface for some reason when you tab out of the game, to a small size, which leads to the mod shrinking to try and fit it. When it's expanded again, it doesn't reverse it, because that's not what you'd normally want.

Soo yeah weird issue I guess, not sure there's anything I can do about it unfortunately.

**Comment by badtouchatr** [comment]
No, it's fine.  I finally figured out how to get around it.  Whenever I want to tab out of Factorio, I just hit escape to pause the game.  When I tab back in, Factory Planner has the right size.  As long as I remember to pause it before tabbing out, it's all fine.  Thanks for your reply, and thanks for a great mod!

**Comment by ClaudeMetz** [comment]
Ah right that makes sense, the mod doesn't receive any events when the game is paused like that, so that's a neat solution. Happy to hear you like the mod!
