### ISSUE TITLE
Incorrect ingredient amounts with productivity and large number of beacons

### ISSUE THREAD

**Issue by VolcanoCookies** [ClaudeMetz/FactoryPlanner#145]
### Problem Description

# Relevant Mods
- [Bobs Modules](https://mods.factorio.com/mod/bobmodules)
- [Bobs Assembling Machines](https://mods.factorio.com/mod/bobassembly)
- Factory Planner version 1.1.72

# The Issue
Given assemblers with productivity modules in them, increasing the amount of beacons beyond a certain point causes the amount of required items to decrease. 
For example these two production lines create the same amount of science with assemblers that have the same amount of productivity modules, but one takes about 50% more ingredients. (And yes, 60 beacons is the max I can fit around an inserter with T3 beacons, gives a total of +21600% speed)
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/45797342/097baa0a-3d23-4638-98ae-a75e94f93100)

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13060652/factorio-current.log)
The save-file is 63MB, I can drop it in a drive if needed but given this isn't a crash issue maybe it is not needed? Let me know!

**Comment by scottmsul** [comment]
This actually isn't a bug in Factory Planner but rather a bug in Factorio. If the crafting speed is more than once per tick, the game extends the productivity bonus as if it were crafting at full speed, but then consumes ingredients at the capped rate of once per tick. The Factorio devs are aware of this, and know it's a problem for mods, but haven't bothered to fix it probably because 1) it can't affect base game, and 2) I'm speculating it would require a rather involved change to the code. But yes, Factory Planner is "correct" in that it matches what the engine does in an actual game.

**Comment by VolcanoCookies** [comment]
Yepp, was just about to close this issue as I tested it in-game.

Averaged the throughput on a single machine vs two running approximately twice as slow.
Not sure how exactly this mod calculates its values but cool to see that it stays true to what would happen in-game even when there is a bug in factorio itself.

# Factory Planner
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/45797342/92d3154a-7681-4421-9fd4-2966c4ea73f7)

# Single Machine
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/45797342/3c9b43de-7d46-4ae7-b702-7482c808742f)

# Two Machines
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/45797342/3d6e7200-5453-4f7d-bc19-f84b0805a339)
