### ISSUE TITLE
Inserter bottleneck

### ISSUE THREAD

**Issue by jwueller** [ClaudeMetz/FactoryPlanner#148]
### Suggestion

Would it be feasible to calculate the number of inserters of a particular grade required to transport the materials in and out?

**Comment by ClaudeMetz** [comment]
It would be possible to kinda approximate it, yes. Predicting inserters is tricky, as it depends on a lot of things, plus there's just tons of types of inserters. I have some plans for it #71, but it'll go along with some other bigger changes. So yes, it's on my radar, but a while off still in all likelyhood. I'll close this one since the above named issue has the same topic.
