### ISSUE TITLE
SE Matter Fabs can have beacons copied to them and end up showing wrong quantities.

### ISSUE THREAD

**Issue by Vovosunt** [ClaudeMetz/FactoryPlanner#156]
You can't set modules or beacons for Space Exploration Matter Fabricators, but you CAN copy beacons from the rest of the factory and paste them onto matter fabricators. This results in planner showing wrong "beaconed" calculations.

**Comment by ClaudeMetz** [comment]
Hm that's a weird one, the mod thinks the fabricators can accept beacons. I'll have to look into what's going on there. Thanks for letting me know.

**Comment by ClaudeMetz** [comment]
I fixed being able to paste beacons that have only incompatible modules for the next release, thanks for the report.

The SE issue is a bit different. It will now not allow you to paste anything invalid onto it anymore, but it'll still show the ability to add beacons, even though you can't add any modules. This is not quite so simple to fix, because figuring out when to show this is quite complicated, and depends on recipe and machine as well. Running that code on each refresh is a bit much, performance-wise, so I'd have to cache the result, and refresh that cache on any change. I'll have to think about it some more. Either way though, any invalid configurations shouldn't be possible anymore now.

**Comment by ClaudeMetz** [comment]
So much about this changed with 2.0 that I'll consider it solved until proven otherwise.
