### ISSUE TITLE
New crash with version 1.1.73

### ISSUE THREAD

**Issue by Active-Link** [ClaudeMetz/FactoryPlanner#157]
### Problem Description

error report from Factorio:

The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/factory_list.lua:277: attempt to index local 'factory' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/factory_list.lua:277: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13398968/factorio-current.log)

### Reproduction

This occurred in multiplayer. Sometimes when someone interacted with their planner another user on the server would crash. Could not identify a specific interaction that caused it.

**Comment by Active-Link** [comment]
Upon further investigation, it appears to be related to compact mode and deleting factories. Both, separately, seem to potentially cause other users to crash.

**Comment by GoneWacko** [comment]
Possibly the same issue: If I start a brand new game (Seablock + Brave New World, but I'm not sure that it matters) and open Factory Planner, go to Preferences, and then switch the "Preffered belt" toggle from "Belts" to "Lanes", it crashes.

The crash does not occur if you have at least one factory created.

**Comment by ClaudeMetz** [comment]
@Active-Link Thanks for the report, that's kind of a weird crash. Seems to be caused by trying to delete the same factory twice. I'm not sure if this is possible, but it might be in multiplayer because of latency, where you can press the button twice before the first one was carried out. Either way, I put some protections in place for that, please open a new issue if it happens to you again with the new release, due out soon.

@GoneWacko Thank you too, that one is not related, but a good spot anyways! I fixed it too for the next release.
