### ISSUE TITLE
Crash when handling factoryplanner::on_gui_hover event when hovering over the compact window

### ISSUE THREAD

**Issue by GoneWacko** [ClaudeMetz/FactoryPlanner#160]
### Problem Description

I have the compact view open and any time I hover over an ingredient, output or byproduct, the GUI crashes.

This is the stack trace:
```
The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_hover (ID 178)
__factoryplanner__/ui/base/compact_dialog.lua:418: attempt to index field '?' (a nil value)
stack traceback:
	__factoryplanner__/ui/base/compact_dialog.lua:418: in function 'handle_hover_change'
	__factoryplanner__/ui/base/compact_dialog.lu
a:496: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```

I did a little bit of debugging myself and the `nil` value appears to be `tags.fuel_id`.

This save file can reproduce the issue consistently for me:
[Crash on_gui_hover.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13400471/Crash.on_gui_hover.zip)

### Reproduction

1. Load the attached save. The compact view of the factory planner should already be up, with the 'Early slag slurry' recipe open.
2. Hover the mouse over any of the ingredients for a little bit and the game crashes.

**Comment by andreimamlay** [comment]
Additional steps to reproduce:

1. Start new game
2. Add new product (ex. wooden chest)
3. Switch to compact view
4. Hover over ingredient - no error
5. Save game
6. Load game
7. Hover over the same ingredient
8.  Crash occurs

**Comment by ClaudeMetz** [comment]
Appreciate the very detailed report, and especially the additional reproduction steps, they really helped me hone in on the cause. This issue basically boils down to me not fully re-indexing some things after a save is loaded, which would cause all kinds of crashes, this one being the most frequent one.

I had a sense of enormous dread overcome me when I first saw this, because I thought my new system was fundamentally flawed in some way. But not, I just forgot to re-index some things. Release due out soon, thanks again.
