### ISSUE TITLE
Update only FP from 72 to 74 produce invalid subfactories

### ISSUE THREAD

**Issue by iassasin** [ClaudeMetz/FactoryPlanner#169]
### Problem Description

Only FP mod update causes broke subfactories, source version is 1.1.72 (is above 1.1.60).

[Savefile (75 MB)](https://sinair.ru/f/S6dbGG?dl=)
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13404444/factorio-current.log)

### Reproduction

1. Has a save file with space exploration mod and FP 1.1.72
2. For example has a subfactory for holmium wire
![изображение](https://github.com/ClaudeMetz/FactoryPlanner/assets/20709774/7e0e2ebc-5a80-4bc9-842a-e9e956f242f1)
3. Update only FP to 1.1.74
4. FP says it need repair
![изображение](https://github.com/ClaudeMetz/FactoryPlanner/assets/20709774/2b8ab985-88af-4f91-b3ab-18d09a730816)
5. After repair the main recipe is missing:
![изображение](https://github.com/ClaudeMetz/FactoryPlanner/assets/20709774/b687d596-179d-4b89-be08-52579d6cd6ee)

UPD: not only recipe is missing. Beacon modules also broken. It was speed modules, but becomes efficiency

**Comment by ClaudeMetz** [comment]
Oh wow, these issues were, unlikely as it is, intertwined. The remark that the modules changed was the important hint, as I noticed my migration script tried to migrate machine modules onto the beacons, which more often than not was just invalid, hence why it removes those lines when repairing. Big oof.

Either way, thanks for the very detailed report. Fixed in the newest release.

**Comment by iassasin** [comment]
Thank you a lot! I'll try the fix as soon as it released
