### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by Marchthemonth** [ClaudeMetz/FactoryPlanner#173]
Updated from 1.1.72 -> 1.1.74, received this error
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/59372888/5f582b2e-516e-4538-9892-f9d9d6ea7b76)

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. Migration issues like these are hard to diagnose without a save file. Could you provide me yours? If it's small enough, you can drop it here on Github.

**Comment by Marchthemonth** [comment]
the save file is 500MB, so here's the Google Drive link instead:
https://drive.google.com/file/d/1vNQcpDL5tDf7sbL1SazV-tkU6BkPA18K/view?usp=sharing

**Comment by ClaudeMetz** [comment]
Thanks. The file seems set to private, I sent a silly request for access.

**Comment by Marchthemonth** [comment]
sorry, fixed. try again.

**Comment by ClaudeMetz** [comment]
Thank you, worked. That's one chonky file! I'll look into the issue.

**Comment by Marchthemonth** [comment]
In an attempt to make it more manageable to open up (since I'm sure you'll be doing that a few times), I took the same one and trimmed/deleted many surfaces
https://drive.google.com/file/d/1vX1ReB3fzqGuHj32kjxKrekhWmmHQMnO/view?usp=sharing

**Comment by ClaudeMetz** [comment]
Thank you, that's very kind.

**Comment by ClaudeMetz** [comment]
Thanks to your save file (and patience), I was able to figure it out. It's related to migrating something that is already 'invalid' due to mod changes, which is something I didn't really test before release.

Although, there do seem to be some migration gremlins still, as most your plans are invalidated, which I'm not sure is working correctly. I'll have to look into that. But this one will be fixed with a release soon.
