### ISSUE TITLE
Show disabled recipes

### ISSUE THREAD

**Issue by LAGIdiot** [ClaudeMetz/FactoryPlanner#235]
### Suggestion

I would like to have option to toggle to show and use disabled recipes.

Py mods (https://mods.factorio.com/user/pyanodon) have T.U.R.D mechanics which allows using different (upgraded) recipes after activating them (by choosing from 3 for same building). Recipes are disabled (I can see them in Recipe Book marked as disabled) before being choosen. And I would like to use Factory Planner with these disabled recipes to compare them with current version I am using.

**Comment by ClaudeMetz** [comment]
Hello, sorry for the late response. This one is quite tricky, because showing disabled recipes always will just inundate the user with crap. Mods use these a lot for hacky scripting reasons. So it would need to be a custom solution, specially done for Py's. I avoided this up till now since it's a giant support burden. I have however had an idea for how to solve this recently, but I don't know when this will actually come to be. Info here #332 (not quite filled in yet)
