### ISSUE TITLE
With full Pyanodon stack, certain recipes are not detected.

### ISSUE THREAD

**Issue by avpas** [ClaudeMetz/FactoryPlanner#300]
### Problem Description

When I try to build a production chain in a Pyanodon game, some recipes are not detected. I click on an ingredient and there is a message at the bottom of the FP window stating "No existing recipe produces this item".
[https://cdn.discordapp.com/attachments/600791114831757416/1242876877002244247/image.png?ex=664f6ecb&is=664e1d4b&hm=ae9499e3e1f1216680729ac25b6b005eac7c17faab9de2f8593ac15fc8986b24&](url)

The recipe is researched, though:
[https://cdn.discordapp.com/attachments/600791114831757416/1242834114885718046/image.png?ex=664f46f7&is=664df577&hm=d1bb0796b246cd5e93eef32e6caff0dc6105a70ad5b2f707eadd272f4a5cf8e1&](url)

**Comment by Slayman** [comment]
I have the same problem as the Original Poster, I can add the following information:
Affected Recipes for me so far are: Boric Acid (boric-acid.10) and Sweet Sirup (sweet-sirup.10)
the names of the things give away the most likely cause of them not being found
The result of the the recipes are called
boric-acid.10
sweet-sirup.10
respectively which makes them invisible to Factory Planner I assume
Factory Planner can currently not ascertain the base fluid from that,
but due to the fact that the recipe result is not boric-acid and sweet-sirup respectively means they cannot be found.
I hope that helps
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/4071149/2bc3452f-1cd0-44a8-bee2-39ff8aa4b680)

**Comment by ClaudeMetz** [comment]
Hello guys, appreciate all the details. This does look like a fluid temp-related issue. It's a topic I am very close to solving, hopefully. Didn't quite make it for 2.0, but I am close. We'll centralize on #95, so closing this one.
