### ISSUE TITLE
Settings to always expand and always group ingredients

### ISSUE THREAD

**Issue by Foeglas** [ClaudeMetz/FactoryPlanner#334]
https://drive.google.com/file/d/1R07oV_2KQMR3lNn4EHT_ZMWQ6Wt30WDw/view?usp=sharing
It takes **too many clicks** to show all the steps to produce an item from raw inputs in FP. The setting to "fold out subfloors" doesn't seem to help. It's especially noticeable with modded items that have many ingredients like the IR3 steam assembler shown in the recording. I even get popups to select a recipe when only a single recipe is available!

I prefer to simply expand everything by default without any additional clicking: https://factoriolab.github.io/ir3/list?o=assembling-machine-1&tre=K&v=11. I can then quickly scroll down to the "ingots" ("plates" in vanilla) to see raw costs. When designing with raw inputs in mind, I usually also want to consolidate them by type. It's useful to see how many copper wires needed by vanilla red circuits themselves vs the copper wires in the green circuits used in red circuits. But I never want to see copper ore in three separate rows like in the recording. Avoiding that seems to require clicking not just many times but in a very deliberate order as well.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the suggestion. You are right that this is a weak point of the mod. The issue is that this kind of system only really works for vanilla, where there are very few products that have more than one recipe. If there are multiple, you'll still need to make choices for what recipes to use.
Still, I do want to support this feature, and I have ideas for how to do it. See #94 for details.
