### ISSUE TITLE
Offsore pump not highlighting valid placements when "Left-Click: put into cursor"

### ISSUE THREAD

**Issue by jmklix** [ClaudeMetz/FactoryPlanner#387]
### Problem Description

When playing the latest version of space age (2.0.13) the offsore pumps are not highlighting valid placement locations when being selected from the compact view. This happens on both Vulcanus (for lava) and Nauvis (for water). I'm assuming it's broken everywhere.

### Reproduction

1. Add offsore pump to factory plan
2. Left click to put it in cursor
3. Don't see valid placements

**Comment by ClaudeMetz** [comment]
Hm that's a tricky one. It's not really a bug actually. When you put an item into your cursor through the mod, it generates a one-entity blueprint for it. That way, it can set a recipe or pre-insert modules. This mode doesn't show the placement locations. The Q-picked entities do show them, but they can't have recipes/modules configured, so I can't really use that one by default.

I potentially could choose which system to use depending on the entity I guess. Which has potential to be confusing too since the two modes work a bit differently. But maybe if there is not recipe or modules, I use the pipette mode. I'll add it to the list of things to look into, thanks.

**Comment by ClaudeMetz** [comment]
Had a look at this, and implemented it like I said: It'll check whether it can use pipette-mode, and use it if so, otherwise fall back to blueprints. So offshore pumps will use pipette, and thus show the placement indicators. Thanks again for the suggestion.
