### ISSUE TITLE
Crushers showing +100% productivity

### ISSUE THREAD

**Issue by Silv3rDragon** [ClaudeMetz/FactoryPlanner#402]
### Problem Description

Any crusher on a basic recipe is showing a blue +100% productivity.  I have no productivity modules and "Asteroid productivity" is not even unlocked, let alone upgraded.
![Screenshot 2024-11-14 151246](https://github.com/user-attachments/assets/adb604a2-5fbe-4147-8a36-c0e844c438fb)

**Comment by ClaudeMetz** [comment]
Thanks for the report. I can't seem to reproduce this situation. Could you provide me your save file?

**Comment by Silv3rDragon** [comment]
> Thanks for the report. I can't seem to reproduce this situation. Could you provide me your save file?

my full game save or just export that factory from the mod?

**Comment by ClaudeMetz** [comment]
Ideally the save file, that way I can sync with your exact mod set and version etc. Makes it easier to diagnose, some issues get lost with the export string.

**Comment by Silv3rDragon** [comment]
[Creative 2.0 bug check.zip](https://github.com/user-attachments/files/17783009/Creative.2.0.bug.check.zip)
finally got the file size small enough to upload, not sure why its so large still compared to other saves.
I deleted all other factories in the factory planner so no hunting for it.

**Comment by ClaudeMetz** [comment]
Thanks for the save! Turns out you have manually overridden the productivity for these recipes in the utility dialog (probably by mistake?). You can have a look at it by clicking the gear icon next to 'Production'. Looks like this:

![Image](https://github.com/user-attachments/assets/bbffdfee-1083-4933-b3e7-dc960f2f892d)

So I'll consider this issue solved, but let me know if there's still an issue. Also, wait until the next release to try this out, as the utility dialog currently crashes when trying to use it in editor mode.

**Comment by Silv3rDragon** [comment]
I updated to 2.0.10 and changed those values.  I must have messed with it at some point then forgot.  Thank you.
