### ISSUE TITLE
Allow non researchable recipes?

### ISSUE THREAD

**Issue by davqvist** [ClaudeMetz/FactoryPlanner#420]
### Suggestion

It seems that non researchable recipes are hidden and not selectable for calculation (unless I am mistaken)
I looked at the options but couldn't find a way to allow them to be selectable (unless I am blind). 
Is there a way to do this? If not, I would love an option to be added to show them. This option doesn't even need to be where you choose between researched or hidden recipes when searching for recipes, it could be a preference checkbox or something if you feel the general user gets confused by this.

Reason being that recipes also can be unlocked by other means like scripts at runtime. Even though this is rare for most mods, I have a use case for a mod that I am developing.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the suggestion. There isn't a way to show them. The mod does a lot of filtering of prototype data to get rid of all the hidden stuff they add for scripting. This is important because it'd be confusing a lot of the time otherwise. 

With that said, there are situations like you said where it would be useful to see disabled recipes. I'm not sure a setting is the way to go though. I had the idea to add an interface for mods to add explicit compatibility though (#332), so yeah that's probably the way I'll go in the future.
